@AskSam_API_HostAddress = http://localhost:5125

GET {{AskSam_API_HostAddress}}/questions/
Accept: application/json

###

GET {{AskSam_API_HostAddress}}/questions/

###

GET {{AskSam_API_HostAddress}}/questions/7ac79c82-b01b-46de-af5c-3d7db4bfeeaf

###

GET {{AskSam_API_HostAddress}}/questions/a21703ea-0ebd-4dc7-80f0-bb4e2e842a8c

###

GET {{AskSam_API_HostAddress}}/questions/getclientid

###

GET {{AskSam_API_HostAddress}}/questions?ids=1&ids=2

###

GET {{AskSam_API_HostAddress}}/questions/0

###
POST {{AskSam_API_HostAddress}}/questions
Content-Type: application/json

{
    "Guid": "7ac79c82-b01b-46de-af5c-3d7db4bfeeaf",
    "Answered": false,
    "Question": "What colour is the sky?",
    "Answer": "",
    "Type": "General"
}

###
POST {{AskSam_API_HostAddress}}/questions
Content-Type: application/json

{
    "Guid": "7ac79c82-b01b-46de-af5c-3d7db4bfeeaf",
    "Answered": true,
    "Question": "What colour is Space?",
    "Answer": "Dark Blue",
    "Type": "General"
}

###
PUT {{AskSam_API_HostAddress}}/questions/0
Content-Type: application/json

{
    "Guid": "7ac79c82-b01b-46de-af5c-3d7db4bfeeaf",
    "Answered": true,
    "Question": "What is my name?",
    "Answer": "Sam",
    "Type": "General"
}

###
DELETE {{AskSam_API_HostAddress}}/questions/0