@AskSam_API_HostAddress = http://localhost:5125
# @AskSam_API_HostAddress = https://asksamapi.azurewebsites.net

GET {{AskSam_API_HostAddress}}/questions/
Accept: application/json

###

GET {{AskSam_API_HostAddress}}/questions/allquestions

### admin guid

GET {{AskSam_API_HostAddress}}/questions/allquestions/02c45e2f-8299-44e2-aa24-0c99fc60c7bd

### random guid

GET {{AskSam_API_HostAddress}}/questions/allquestions/d2c96a35-40ef-45a3-8d06-b694deab439c


###

GET {{AskSam_API_HostAddress}}/questions/3327cf26-f40c-4b21-8643-813d8dc47af4
###

GET {{AskSam_API_HostAddress}}/questions/5c7dd3fd-237e-40b6-96e7-19913f1ecb0d/

###

GET {{AskSam_API_HostAddress}}/questions/5c7dd3fd-237e-40b6-96e7-19913f1ecb0d/8

###

GET {{AskSam_API_HostAddress}}/questions/getclientid

###
POST {{AskSam_API_HostAddress}}/questions
Content-Type: application/json

{
    "clientGuid": "7ac79c82-b01b-46de-af5c-3d7db4bfeeaf",
    "Answered": false,
    "Question": "What colour is the sky?",
    "Answer": "",
    "Type": "General"
}

###
POST {{AskSam_API_HostAddress}}/questions
Content-Type: application/json

{
    "clientGuid": "7ac79c82-b01b-46de-af5c-3d7db4bfeeaf",
    "Answered": true,
    "Question": "What colour is Space?",
    "Answer": "Dark Blue",
    "Type": "General"
}

###
PUT {{AskSam_API_HostAddress}}/questions/5ae1007b-5f07-431f-b08a-96823dbbcaf6
Content-Type: application/json

{
    "ClientGuid": "7bc984bb-43d5-4c77-9e1c-b1a3c1fae2c6",
    "Answered": true,
    "Question": "What is my name?",
    "Answer": "Sam",
    "Type": "General"
}

###
DELETE {{AskSam_API_HostAddress}}/questions/2a8a2480-70f7-414f-b049-24a2569e7e56